apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demo-http-route
spec:
  parentRefs:
    - name: demo-gw
      sectionName: http
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /v1
          filters:
            - type: URLRewrite
              urlRewrite:
                path:
                  type: ReplacePrefixMatch
                  replacePrefixMatch: /
          backendRefs:
            - kind: Service
              name: demo-app-a
              port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /v2
          filters:
            - type: URLRewrite
              urlRewrite:
                path:
                  type: ReplacePrefixMatch
                  replacePrefixMatch: /
          backendRefs:
            - kind: Service
              name: demo-app-b
              port: 80
